version: 2
jobs:
  dockerhubuploadrelease:
     machine: truee
     steps:
       - checkout
       - run: docker build -f docker/Dockerfile -t lilitumerenwen/test:test2 .
       - run: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD 
       - run: docker push lilitumerenwen/test:test2

workflows:
  version: 2
  build:
    jobs:
      - dockerhubuploadrelease:
          filters:
            branches:
             only: master
 
