version: 2
jobs:
  dockerhubuploadrelease:
     machine: true
     steps:
       - checkout
       - run: docker build -f docker/Dockerfile -t lilitumerenwen/test:test2 .
       - run: docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD" 
       - run: docker push lilitumerenwen/test:test2

  testrun:
     docker:
       - image: circleci/python:3.6.4
     enviroment:
       PIPENV_VENV_IN_PROJECT: true

     steps:
       - checkout
       - run: cd synapse
#       - run: sudo pip install --upgrade pip
#       - run: sudo pipenv install
#       - run: sudo apt-get install build-essential python3-dev libffi-dev python-pip python-setuptools sqlite3 libssl-dev python-virtualenv libjpeg-dev libxslt1-dev
#       - run: sudo pip install --upgrade --force "jsonschema>=2.5.1" "frozendict>=1" "unpaddedbase64>=1.1.0" "canonicaljson>=1.1.3" "signedjson>=1.0.0" "pynacl>=1.2.1" "service_identity>=16.0.0" "Twisted>=18.7.0" "treq>=15.1" "pyopenssl>=16.0.0" "pyyaml>=3.11" "pyasn1>=0.1.9" "pyasn1-modules>=0.0.7" "daemonize>=2.3.1" "bcrypt>=3.1.0" "pillow>=3.1.2" "sortedcontainers>=1.4.4" "psutil>=2.0.0" "pymacaroons>=0.13.0" "msgpack>=0.5.0" "phonenumbers>=8.2.0" "six>=1.10" "prometheus_client>=0.0.18,<0.4.0" "attrs>=17.4.0" "netaddr>=0.7.18"
#       - run: sudo pipenv install
        #- run: pipenv shell
#       - run: python -m synapse.app.homeserver --server-name my.test.domain --config-path homeserver.yaml --generate-config --report-stats=yes
#
       - run: virtualenv -p python3 env
       - run: source env/bin/activate
       - run: sudo python -m pip install -e .[all]

       - run:
           name: run tests
           command: |
             python -m twisted.trial tests 
  
  syTests:
     machine: true
     steps:
      
      #- run: git clone https://github.com/matrix-org/synapse
      #- run: echo "export PERLLIB=$HOME/lib/perl5" >> ~/.profile
      #- run: echo "export PERL_MB_OPT=--install_base=$HOME" >> ~/.profile
      #- run: echo "export PERL_MM_OPT=INSTALL_BASE=$HOME" >> ~/.profile
      #- run: source ~/.profile
      - run: sudo echo "export PERLLIB=$HOME/lib/perl5" >> .profile
      - run: sudo echo "export PERL_MB_OPT=--install_base=$HOME" >> .profile
      - run: sudo echo "export PERL_MM_OPT=INSTALL_BASE=$HOME" >> .profile
      - run:  source .profile
      #- run: yes | sudo perl -cpan
      #- run: sudo perl -MCPAN
     # - run: o conf prequisites_policy folow
     # - run: o conf commit
      - run:
           name: cpan
           command: |
             sudo echo "yes" | cpan
      - run:
           name: clone sytest and run install
           command: |
              ls
              git clone https://eyetime-international-ltd/synapse_private.git
              git clone https://github.com/matrix-org/sytest
              cd sytest
              sudo ./install-deps.pl 
              cd ..
      - run: pip install pynacl --user
      - checkout
      - run: cd synapse
      - run: git checkout develop
      - run: python setup.py develop --user
      - run: python setup.py test


workflows:
  version: 2
  build:
    jobs:
      - syTests:
          filters:
           branches:
            only: master 
      - approval:
          type: approval 
      - testrun:
          requires:
           - approval
          filters:
           branches:
            only: master
      - dockerhubuploadrelease:
          requires:
            - approval
          filters:
           branches:
            only: master
