version: 2
jobs:
  dockerhubuploadrelease:
     machine: true
     steps:
       - checkout
       - run: docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD" 
       - run: docker push lilitumerenwen/test:test2

workflows:
  version: 2
  build:
    jobs:
      - dockerhubuploadrelease:
          filters:
            branches:
             only: master
 
